vars: {
  d2-config: {
    theme-id: 200
  }
}

Clients: {
  Admin: {
    label: "Administrator"
    shape: person
  }

  Client: {
    label: "Client\n(Web Browser)"
    shape: cylinder
  }

  User: {
    label: "Customer"
    shape: person
  }
}

Frontend: {
  label: "Frontend\n(React, TypeScript)"
  grid-rows: 2
  index
  signin
  signup
  orders
  checkout
  products: {
    index
    create
    "id/{product id}"
  }
  admin: {
    discounts
    orders
    users
  }
}

Backend: {
  Phobost API: {
    /v1/health
    /v1/md2html
  }
  Firebase: {
    Firestore API
    Storage API
    Authentication API
  }
}

Firebase Storage: {
  shape: cylinder
}

Firestore: {
  shape: cylinder
}

Firebase Authentication: {
  shape: Person
}

# Primary Connections
Clients -> Frontend: "Renders UI"

Frontend -> Backend.Firebase: "Signs in or signs out users"
Frontend -> Backend.Firebase: "Stores product images"
Frontend -> Backend.Firebase: "General storage, product listings, orders, discounts, etc."
Frontend -> Backend.Phobost API: "Converts product page markdown to HTML"

Backend.Firebase.Firestore API -> Firestore
Backend.Firebase.Storage API -> Firebase Storage
Backend.Firebase.Authentication API -> Firebase Authentication
